### ISSUE TITLE
Outdated

### ISSUE THREAD

**Issue by jektall** [globelabs/globe-connect-nodejs#2]
npm WARN deprecated minimatch@1.0.0: Please update to minimatch 3.0.2 or higher to avoid a RegExp DoS issue
npm WARN deprecated minimatch@2.0.10: Please update to minimatch 3.0.2 or higher to avoid a RegExp DoS issue
npm WARN notice [SECURITY] minimatch has the following vulnerability: 1 high. Go here for more details: https://nodesecurity.io/advisories?search=minimatch&version=2.0.10 - Run `npm i npm@latest -g` to upgrade your npm version, and then `npm audit` to get more info.
npm WARN notice [SECURITY] minimatch has the following vulnerability: 1 high. Go here for more details: https://nodesecurity.io/advisories?search=minimatch&version=1.0.0 - Run `npm i npm@latest -g` to upgrade your npm version, and then `npm audit` to get more info.

> node-libcurl@1.0.0 install C:\xampp\htdocs\events\globepayment\node_modules\node-libcurl
> node-pre-gyp install --fallback-to-build

node-pre-gyp info it worked if it ends with ok
node-pre-gyp verb cli [ 'C:\\Program Files\\nodejs\\node.exe',
node-pre-gyp verb cli   'C:\\xampp\\htdocs\\events\\globepayment\\node_modules\\node-libcurl\\node_modules\\node-pre-gyp\\bin\\node-pre-gyp',
node-pre-gyp verb cli   'install',
node-pre-gyp verb cli   '--fallback-to-build' ]
node-pre-gyp info using node-pre-gyp@0.6.28
node-pre-gyp info using node@8.11.2 | win32 | x64
node-pre-gyp verb command install []
node-pre-gyp info check checked for "C:\xampp\htdocs\events\globepayment\node_modules\node-libcurl\lib\binding\node_libcurl.node" (not found)
node-pre-gyp http GET https://github.com/JCMais/node-libcurl/releases/download/v1.0.0/node_libcurl-v1.0.0-node-v57-win32-x64.tar.gz
node-pre-gyp http 404 https://github.com/JCMais/node-libcurl/releases/download/v1.0.0/node_libcurl-v1.0.0-node-v57-win32-x64.tar.gz
node-pre-gyp ERR! Tried to download: https://github.com/JCMais/node-libcurl/releases/download/v1.0.0/node_libcurl-v1.0.0-node-v57-win32-x64.tar.gz
node-pre-gyp ERR! Pre-built binaries not found for node-libcurl@1.0.0 and node@8.11.2 (node-v57 ABI) (falling back to source compile with node-gyp)
node-pre-gyp http Pre-built binary not available for your system, looked for https://github.com/JCMais/node-libcurl/releases/download/v1.0.0/node_libcurl-v1.0.0-node-v57-win32-x64.tar.gz
node-pre-gyp verb command build [ 'rebuild' ]
gyp ERR! configure error
gyp ERR! stack Error: Can't find Python executable "python", you can set the PYTHON env variable.
gyp ERR! stack     at PythonFinder.failNoPython (C:\Program Files\nodejs\node_modules\npm\node_modules\node-gyp\lib\configure.js:483:19)
gyp ERR! stack     at PythonFinder.<anonymous> (C:\Program Files\nodejs\node_modules\npm\node_modules\node-gyp\lib\configure.js:508:16)
gyp ERR! stack     at C:\Program Files\nodejs\node_modules\npm\node_modules\graceful-fs\polyfills.js:284:29
gyp ERR! stack     at FSReqWrap.oncomplete (fs.js:152:21)
gyp ERR! System Windows_NT 10.0.16299
gyp ERR! command "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\node_modules\\node-gyp\\bin\\node-gyp.js" "configure" "--fallback-to-build" "--module=C:\\xampp\\htdocs\\events\\globepayment\\node_modules\\node-libcurl\\lib\\binding\\node_libcurl.node" "--module_name=node_libcurl" "--module_path=C:\\xampp\\htdocs\\events\\globepayment\\node_modules\\node-libcurl\\lib\\binding"
gyp ERR! cwd C:\xampp\htdocs\events\globepayment\node_modules\node-libcurl
gyp ERR! node -v v8.11.2
gyp ERR! node-gyp -v v3.6.2
gyp ERR! not ok
node-pre-gyp ERR! build error
node-pre-gyp ERR! stack Error: Failed to execute 'C:\Program Files\nodejs\node.exe C:\Program Files\nodejs\node_modules\npm\node_modules\node-gyp\bin\node-gyp.js configure --fallback-to-build --module=C:\xampp\htdocs\events\globepayment\node_modules\node-libcurl\lib\binding\node_libcurl.node --module_name=node_libcurl --module_path=C:\xampp\htdocs\events\globepayment\node_modules\node-libcurl\lib\binding' (1)
node-pre-gyp ERR! stack     at ChildProcess.<anonymous> (C:\xampp\htdocs\events\globepayment\node_modules\node-libcurl\node_modules\node-pre-gyp\lib\util\compile.js:83:29)
node-pre-gyp ERR! stack     at emitTwo (events.js:126:13)
node-pre-gyp ERR! stack     at ChildProcess.emit (events.js:214:7)
node-pre-gyp ERR! stack     at maybeClose (internal/child_process.js:925:16)
node-pre-gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:209:5)
node-pre-gyp ERR! System Windows_NT 10.0.16299
node-pre-gyp ERR! command "C:\\Program Files\\nodejs\\node.exe" "C:\\xampp\\htdocs\\events\\globepayment\\node_modules\\node-libcurl\\node_modules\\node-pre-gyp\\bin\\node-pre-gyp" "install" "--fallback-to-build"
node-pre-gyp ERR! cwd C:\xampp\htdocs\events\globepayment\node_modules\node-libcurl
node-pre-gyp ERR! node -v v8.11.2
node-pre-gyp ERR! node-pre-gyp -v v0.6.28
node-pre-gyp ERR! not ok
Failed to execute 'C:\Program Files\nodejs\node.exe C:\Program Files\nodejs\node_modules\npm\node_modules\node-gyp\bin\node-gyp.js configure --fallback-to-build --module=C:\xampp\htdocs\events\globepayment\node_modules\node-libcurl\lib\binding\node_libcurl.node --module_name=node_libcurl --module_path=C:\xampp\htdocs\events\globepayment\node_modules\node-libcurl\lib\binding' (1)
npm WARN globepayment@1.0.0 No description
npm WARN globepayment@1.0.0 No repository field.

npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! node-libcurl@1.0.0 install: `node-pre-gyp install --fallback-to-build`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the node-libcurl@1.0.0 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\Angelo Franco Manzo\AppData\Roaming\npm-cache\_logs\2018-08-25T06_37_58_180Z-debug.log

**Comment by IvanCurada** [comment]
@jektall I got the same error too :(

npm WARN deprecated minimatch@1.0.0: Please update to minimatch 3.0.2 or higher to avoid a RegExp DoS issue
npm WARN deprecated minimatch@2.0.10: Please update to minimatch 3.0.2 or higher to avoid a RegExp DoS issue

> node-libcurl@1.0.0 install D:\heroku\node_modules\node-libcurl
> node-pre-gyp install --fallback-to-build

node-pre-gyp info it worked if it ends with ok
node-pre-gyp verb cli [ 'C:\\Program Files\\nodejs\\node.exe',
node-pre-gyp verb cli   'D:\\heroku\\node_modules\\node-libcurl\\node_modules\\node-pre-gyp\\bin\\node-pre-gyp',
node-pre-gyp verb cli   'install',
node-pre-gyp verb cli   '--fallback-to-build' ]
node-pre-gyp info using node-pre-gyp@0.6.28
node-pre-gyp info using node@10.1.0 | win32 | x64
node-pre-gyp verb command install []
node-pre-gyp info check checked for "D:\heroku\node_modules\node-libcurl\lib\binding\node_libcurl.node" (not found)
node-pre-gyp http GET https://github.com/JCMais/node-libcurl/releases/download/v1.0.0/node_libcurl-v1.0.0-node-v64-win32-x64.tar.gz
node-pre-gyp http 404 https://github.com/JCMais/node-libcurl/releases/download/v1.0.0/node_libcurl-v1.0.0-node-v64-win32-x64.tar.gz
node-pre-gyp ERR! Tried to download: https://github.com/JCMais/node-libcurl/releases/download/v1.0.0/node_libcurl-v1.0.0-node-v64-win32-x64.tar.gz
node-pre-gyp ERR! Pre-built binaries not found for node-libcurl@1.0.0 and node@10.1.0 (node-v64 ABI) (falling back to source compile with node-gyp)
node-pre-gyp http Pre-built binary not available for your system, looked for https://github.com/JCMais/node-libcurl/releases/download/v1.0.0/node_libcurl-v1.0.0-node-v64-win32-x64.tar.gz
node-pre-gyp verb command build [ 'rebuild' ]
gyp ERR! configure error
gyp ERR! stack Error: Can't find Python executable "C:\Users\ASUS\Anaconda3\python.EXE", you can set the PYTHON env variable.
gyp ERR! stack     at PythonFinder.failNoPython (C:\Users\ASUS\AppData\Roaming\npm\node_modules\npm\node_modules\node-gyp\lib\configure.js:483:19)
gyp ERR! stack     at PythonFinder.<anonymous> (C:\Users\ASUS\AppData\Roaming\npm\node_modules\npm\node_modules\node-gyp\lib\configure.js:508:16)
gyp ERR! stack     at C:\Users\ASUS\AppData\Roaming\npm\node_modules\npm\node_modules\graceful-fs\polyfills.js:284:29
gyp ERR! stack     at FSReqWrap.oncomplete (fs.js:165:21)
gyp ERR! System Windows_NT 10.0.17134
gyp ERR! command "C:\\Program Files\\nodejs\\node.exe" "C:\\Users\\ASUS\\AppData\\Roaming\\npm\\node_modules\\npm\\node_modules\\node-gyp\\bin\\node-gyp.js" "configure" "--fallback-to-build" "--module=D:\\heroku\\node_modules\\node-libcurl\\lib\\binding\\node_libcurl.node" "--module_name=node_libcurl" "--module_path=D:\\heroku\\node_modules\\node-libcurl\\lib\\binding"
gyp ERR! cwd D:\heroku\node_modules\node-libcurl
gyp ERR! node -v v10.1.0
gyp ERR! node-gyp -v v3.6.2
gyp ERR! not ok
node-pre-gyp ERR! build error
node-pre-gyp ERR! stack Error: Failed to execute 'C:\Program Files\nodejs\node.exe C:\Users\ASUS\AppData\Roaming\npm\node_modules\npm\node_modules\node-gyp\bin\node-gyp.js configure --fallback-to-build --module=D:\heroku\node_modules\node-libcurl\lib\binding\node_libcurl.node --module_name=node_libcurl --module_path=D:\heroku\node_modules\node-libcurl\lib\binding' (1)
node-pre-gyp ERR! stack     at ChildProcess.<anonymous> (D:\heroku\node_modules\node-libcurl\node_modules\node-pre-gyp\lib\util\compile.js:83:29)
node-pre-gyp ERR! stack     at ChildProcess.emit (events.js:182:13)
node-pre-gyp ERR! stack     at maybeClose (internal/child_process.js:957:16)
node-pre-gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:246:5)
node-pre-gyp ERR! System Windows_NT 10.0.17134
node-pre-gyp ERR! command "C:\\Program Files\\nodejs\\node.exe" "D:\\heroku\\node_modules\\node-libcurl\\node_modules\\node-pre-gyp\\bin\\node-pre-gyp" "install" "--fallback-to-build"
node-pre-gyp ERR! cwd D:\heroku\node_modules\node-libcurl
node-pre-gyp ERR! node -v v10.1.0
node-pre-gyp ERR! node-pre-gyp -v v0.6.28
node-pre-gyp ERR! not ok
Failed to execute 'C:\Program Files\nodejs\node.exe C:\Users\ASUS\AppData\Roaming\npm\node_modules\npm\node_modules\node-gyp\bin\node-gyp.js configure --fallback-to-build --module=D:\heroku\node_modules\node-libcurl\lib\binding\node_libcurl.node --module_name=node_libcurl --module_path=D:\heroku\node_modules\node-libcurl\lib\binding' (1)
npm WARN heroku@1.0.0 No description
npm WARN heroku@1.0.0 No repository field.

npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! node-libcurl@1.0.0 install: `node-pre-gyp install --fallback-to-build`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the node-libcurl@1.0.0 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\ASUS\AppData\Roaming\npm-cache\_logs\2018-08-30T10_24_44_242Z-debug.log

**Comment by jrayga** [comment]
Did you guys solve this problem? I'm using this with firebase cloud function but I can't seem to install this in my cloud functions project. 

I'm having this problem on my end.

> node-pre-gyp ERR! node -v v8.10.0
node-pre-gyp ERR! node-pre-gyp -v v0.6.28
node-pre-gyp ERR! not ok 
Failed to execute /usr/bin/node/usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js configure --fallback-to-build --
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! node-libcurl@1.0.0 install: node-pre-gyp install --fallback-to-build
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the node-libcurl@1.0.0 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
npm ERR! A complete log of this run can be found in:
npm ERR! .npm/_logs/2018-10-23T10_12_14_620Z-debug.log

**Comment by jektall** [comment]
That node version is on meta testing only that's why we're getting that
error. (0.0.2?)

**Comment by rlaurente** [comment]
any fixes for this error ?

Thanks

**Comment by lohwa** [comment]
Good day,,   is there already a solution for this..?  thank you..

**Comment by kebaranas** [comment]
I solved it by downgrading my node js version to 6.14.1 and then installing node-libcurl with version 1.0.0. However, I can't use Firebase functions since it requires a node js version of at least 8.0.0

**Comment by kebaranas** [comment]
Check my forked module. I updated its node libcurl dependency to the latest version. I also tried using it on Firebase Functions (authentication and receiving sms). Check the rest of the features if it work as well. FYI, Firebase Functions Spark (Free version) will not allow any outgoing network responses, so you can't use it on Firebase Functions if you don't upgrade it to either Blaze or Flame.

**Comment by kebaranas** [comment]
I was able to update the node libcurl of the original file, fixed some of the misspellings and variable or constant mismatch. Look at my forked module. As of now, I was able to use the send and receive SMS. Check whether the other functions work as well. I was able to use it on Firebase Functions as well. FYI, you need to upgrade your Firebase plan to either Flame or Blaze to deal with outgoing network requests.

**Comment by kebaranas** [comment]
> Did you guys solve this problem? I'm using this with firebase cloud function but I can't seem to install this in my cloud functions project.
> 
> I'm having this problem on my end.
> 
> > node-pre-gyp ERR! node -v v8.10.0
> > node-pre-gyp ERR! node-pre-gyp -v v0.6.28
> > node-pre-gyp ERR! not ok
> > Failed to execute /usr/bin/node/usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js configure --fallback-to-build --
> > npm ERR! code ELIFECYCLE
> > npm ERR! errno 1
> > npm ERR! node-libcurl@1.0.0 install: node-pre-gyp install --fallback-to-build
> > npm ERR! Exit status 1
> > npm ERR!
> > npm ERR! Failed at the node-libcurl@1.0.0 install script.
> > npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
> > npm ERR! A complete log of this run can be found in:
> > npm ERR! .npm/_logs/2018-10-23T10_12_14_620Z-debug.log

I updated the node libcurl dependency of the package. I was able to use it on Firebase Functions as well. Although in order to use it you have to upgrade yung Firebase plan.

**Comment by hamacjumar** [comment]
> I solved it by downgrading my node js version to 6.14.1 and then installing node-libcurl with version 1.0.0. However, I can't use Firebase functions since it requires a node js version of at least 8.0.0

Does it mean, i can't use globe-connect for the current version of node v12.13.0?

**Comment by kebaranas** [comment]
This is a very old comment. I was actually able to solve it by editing the original globelabs repo. I just updated its node libcurl dependency and checked if it is still using the same api names. Check my forked repo for this.

**Comment by lohwa** [comment]
Thank you very much for the reply..
